apiVersion: v1
kind: Service
metadata:
  name: cluster-service
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - nodePort: 31300
      port: 81
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: myweb
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: myweb
      labels:
        app: webapp
    spec:
      containers:
      - name: myweb-image
        image: butoniya/webserver
